class EuNationCodes {
  EuNationCodes._();

  static const Map<int, String> names = {
    0: 'Bilgi yok',
    1: 'Avusturya',
    2: 'Arnavutluk',
    3: 'Andorra',
    4: 'Ermenistan',
    5: 'Azerbaycan',
    6: 'Belçika',
    7: 'Bulgaristan',
    8: 'Bosna-Hersek',
    9: 'Belarus',
    10: 'İsviçre',
    11: 'Kıbrıs',
    12: 'Çekya',
    13: 'Almanya',
    14: 'Danimarka',
    15: 'İspanya',
    16: 'Estonya',
    17: 'Fransa',
    18: 'Finlandiya',
    19: 'Lihtenştayn',
    20: 'Faroe Adaları',
    21: 'Birleşik Krallık',
    22: 'Gürcistan',
    23: 'Yunanistan',
    24: 'Macaristan',
    25: 'Hırvatistan',
    26: 'İtalya',
    27: 'İrlanda',
    28: 'İzlanda',
    29: 'Kazakistan',
    30: 'Lüksemburg',
    31: 'Litvanya',
    32: 'Letonya',
    33: 'Malta',
    34: 'Monako',
    35: 'Moldova',
    36: 'Kuzey Makedonya',
    37: 'Norveç',
    38: 'Hollanda',
    39: 'Portekiz',
    40: 'Polonya',
    41: 'Romanya',
    42: 'San Marino',
    43: 'Rusya',
    44: 'İsveç',
    45: 'Slovakya',
    46: 'Slovenya',
    47: 'Türkmenistan',
    48: 'Türkiye',
    49: 'Ukrayna',
    50: 'Vatikan',
    51: 'Yugoslavya',
    52: 'Karadağ',
    53: 'Sırbistan',
    54: 'Özbekistan',
    55: 'Tacikistan',
    56: 'Kırgızistan',
    57: 'İsrail',
    253: 'Avrupa Topluluğu',
    254: 'Avrupa\'nın geri kalanı',
    255: 'Dünyanın geri kalanı',
  };

  static String label(int code) => names[code] ?? 'Bilinmeyen ülke (kod $code)';
}
